import React from 'react';
import { Box, Heading, Text, VStack } from '@chakra-ui/react';
import Sidebar from './Sidebar';

const GeneratedIdeas = () => {
  return (
    <Box display="flex" width="100vw" height="100vh" alignItems="center" justifyContent="center">
      <Sidebar currentPath={'/'} />
      <Box flex="1" padding="2rem" overflowY="auto">
        <VStack spacing={6} align="start" maxWidth="600px" margin="0 auto">
          <Heading>Get Inspired</Heading>
          <Text>Choose an idea to build some posts</Text>
          {Array.from({ length: 6 }, (_, i) => (
            <Box key={i} padding="1rem" borderWidth="1px" borderRadius="md" width="100%">
              Idea generated by AI {i + 1}
            </Box>
          ))}
        </VStack>
      </Box>
    </Box>
  );
};

export default GeneratedIdeas;